// vue-3-drag-n-drop/src/components/PhotoUploader.vue
<template>
  <div class="photo-uploader">
    <div
      class="photo-uploader__wrapper"
      :class="{ 'photo-uploader__wrapper--drag': isDragStarted }"
    >
      <input
        ref="input"
        type="file"
        class="photo-uploader__input"
        title=""
        multiple
        @change="uploadFile"
        @dragenter="isDragStarted = true"
        @dragleave="isDragStarted = false"
      >
      {{ isDragStarted ? '' : uploadText }}
      <img
        v-show="isDragStarted"
        class="photo-uploader__icon"
        src="@/assets/images/upload.svg"
        alt="Upload"
      >
    </div>
    <div class="photo-uploader__photos">
      <div
        v-for="(photo, index) in modelValue"
        :key="index"
        class="photo-uploader__photo"
      >
        <button
          class="photo-uploader__remove"
          @click="removePhoto(index)"
        />
        <img
          :src="getSrc(photo)"
          :alt="`Фотография ${index + 1}`"
        >
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {
  computed,
  defineComponent,
  PropType,
  ref,
  toRefs,
} from 'vue';

export default defineComponent({
  props: {
    modelValue: {
      type: Array as PropType<Array<File>>,
      required: true,
    },
  },

  emits: ['update:modelValue'],

  setup(props, { emit }) {
    const { modelValue } = toRefs(props);

    const input = ref<HTMLInputElement | null>(null);
    const isDragStarted = ref(false);

    const uploadFile = ({ currentTarget }: Event & { currentTarget: HTMLInputElement }) => {
      if (currentTarget.files) {
        emit('update:modelValue', [...modelValue.value, ...Array.from(currentTarget.files)]);
      }

      if (input.value) {
        input.value.value = '';
      }

      isDragStarted.value = false;
    };

    const removePhoto = (index: number) => {
      emit('update:modelValue', modelValue.value.filter((p, i) => i !== index));
    };

    const getSrc = (photo: File) => URL.createObjectURL(photo);

    const needToUpload = computed(() => 3 - modelValue.value.length);

    const uploadText = computed(() => {
      if (needToUpload.value > 0) {
        return `Загрузите ${needToUpload.value} ${needToUpload.value === 1 ? 'вашу фотографию' : 'ваши фотографии'}`;
      }

      if (needToUpload.value === 0) {
        return 'Вы загрузили все фотографии';
      }

      return 'Вы загрузили слишком много фотографий';
    });

    return {
      needToUpload,
      uploadFile,
      input,
      isDragStarted,
      getSrc,
      removePhoto,
      uploadText,
    };
  },
});
</script>

<style lang="scss">
.photo-uploader {
  &__wrapper {
    position: relative;
    text-align: center;
    height: 150px;
    display: flex;
    justify-content: center;
    align-items: center;
    border: 4px dotted #eee;
    border-radius: 10px;
    color: rgba(#000, 0.5);

    &--drag {
      color: rgba(#fff, 0);
      border-color: #777;
    }
  }

  &__input {
    cursor: pointer;
    position: absolute;
    z-index: 2;
    top: 0;
    right: 0;
    bottom: 0;
    width: 100%;
    left: 0;
    opacity: 0;
  }

  &__photos {
    display: flex;
    margin-top: 20px;
  }

  &__photo {
    position: relative;
    width: 200px;
    margin-right: 60px;

    img {
      border-radius: 10px;
    }
  }

  &__remove {
    cursor: pointer;
    position: absolute;
    outline: none;
    top: 0;
    left: calc(100% + 10px);
    width: 30px;
    height: 30px;
    border-radius: 50%;
    background-color: rgba(#000, 0.05);
    border: 0;

    &::before {
      content: "";
      position: absolute;
      z-index: 1;
      top: calc(50% - 1px);
      left: calc(50% - 5px);
      width: 10px;
      height: 2px;
      background-color: #000;
    }
  }

  &__icon {
    opacity: 0.3;
    width: 50px;
  }
}
</style>

// react-drag-n-drop/src/components/PhotoUploader/index.tsx
import React, { useMemo, useRef, useState } from 'react';
import './style.scss';

function PhotoUploader({ value, onChange }: { value: Array<File>; onChange: (files: Array<File>) => void }) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  const [isDragStarted, setDragStarted] = useState(false);

  const uploadFile = (files: FileList | null) => {
    if (files) {
      onChange([...value, ...Array.from(files)])
    }

    if (inputRef.current) {
      inputRef.current.value = '';
    }

    setDragStarted(false);
  };

  const removePhoto = (index: number) => {
    onChange(value.filter((p: File, i: number) => i !== index));
  };

  const getSrc = (photo: File) => URL.createObjectURL(photo);

  const needToUpload = useMemo(() => 3 - value.length, [value]);

  const uploadText = useMemo(() => {
    if (needToUpload > 0) {
      return `Загрузите ${needToUpload} ${needToUpload === 1 ? 'вашу фотографию' : 'ваши фотографии'}`;
    }

    if (needToUpload === 0) {
      return 'Вы загрузили все фотографии';
    }

    return 'Вы загрузили слишком много фотографий';
  }, [needToUpload]);

  return (
    <div className="photo-uploader">
      <div
        className={`photo-uploader__wrapper${isDragStarted ? 'photo-uploader__wrapper--drag' : ''}`}
      >
        <input
          ref={inputRef}
          type="file"
          className="photo-uploader__input"
          title=""
          multiple
          onChange={(e) => {
            uploadFile(e.currentTarget.files);
          }}
          onDragEnter={() => setDragStarted(true)}
          onDragLeave={() => setDragStarted(false)}
        />
        {isDragStarted ? '' : uploadText}
        {isDragStarted && (
          <img
            className="photo-uploader__icon"
            src={require('../../assets/images/upload.svg')}
            alt="Upload"
          />
        )}
      </div>
      <div className="photo-uploader__photos">
        {value.map((photo, index) => (
          <div
            key={index}
            className="photo-uploader__photo"
          >
            <button
              className="photo-uploader__remove"
              onClick={() => removePhoto(index)}
            />
            <img
              src={getSrc(photo)}
              alt={`Фотография ${index + 1}`}
            />
          </div>
        ))}
      </div>
    </div>
  );
}

export default PhotoUploader;
