// vue-3-drag-n-drop/src/App.vue
<template>
  <PhotoUploader v-model="files" />
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import PhotoUploader from '@/components/PhotoUploader.vue';

export default defineComponent({
  components: {
    PhotoUploader,
  },

  setup() {
    const files = ref<Array<File>>([]);

    return { files };
  },
});
</script>

<style lang="scss">
@import "~@/assets/scss/global.scss";
</style>

// react-drag-n-drop/src/App.tsx
import React, { useState } from 'react';
import PhotoUploader from './components/PhotoUploader';

function App() {
  const [files, setFiles] = useState<Array<File>>([]);

  return (
    <div className="App">
      <PhotoUploader value={files} onChange={setFiles} />
    </div>
  );
}

export default App;
